;;;; stream.import.scm - GENERATED BY CHICKEN 5.1.0 -*- Scheme -*-

(scheme#eval '(import-syntax scheme chicken.base))
(##sys#register-compiled-module
  'stream
  'stream
  (scheme#list)
  '((stream-car . stream#stream-car)
    (stream-cdr . stream#stream-cdr)
    (stream-null? . stream#stream-null?)
    (the-empty-stream . stream#the-empty-stream)
    (stream-map . stream#stream-map)
    (stream-filter . stream#stream-filter)
    (stream-first . stream#stream-first)
    (stream-take . stream#stream-take)
    (stream-accumulate . stream#stream-accumulate)
    (stream-add . stream#stream-add)
    (stream-zip . stream#stream-zip)
    (integers-starting-from . stream#integers-starting-from)
    (primes . stream#primes)
    (prime? . stream#prime?))
  (scheme#list
    (scheme#cons 'cons-stream (syntax-rules () ((_ a b) (cons a (delay b))))))
  (scheme#list))

;; END OF FILE
